### ISSUE TITLE
The plan for improving the solver interface

### ISSUE THREAD

**Issue by chkwon** [vidalt/HGS-CVRP#12]
### Dev Environment
- [x] `CMake`, `.gitignore` https://github.com/vidalt/HGS-CVRP/pull/8 https://github.com/vidalt/HGS-CVRP/pull/9
- [x] Use `CMake` and `ctest` in CI actions to check the solution correctness https://github.com/vidalt/HGS-CVRP/pull/14

### Interface
- [x] time measure improvement, floating `timeLimit`https://github.com/vidalt/HGS-CVRP/commit/47848a5176e2b51511fdc01bc7009df966c2053c https://github.com/vidalt/HGS-CVRP/commit/623d82150dfeb27e170873bdcf2c448cfbae2559
- [x] refactoring `Params`, file read by `CVRPLIB` https://github.com/vidalt/HGS-CVRP/pull/13
- [x] Algorithm parameters control https://github.com/vidalt/HGS-CVRP/pull/16
- [x] `extern "C"` interface for Python/Julia wrappers https://github.com/vidalt/HGS-CVRP/pull/18

### New features
- [x] verbose control for solver logs https://github.com/vidalt/HGS-CVRP/pull/15
- [x] turn off SWAP* local search for dist_mtx only instances https://github.com/vidalt/HGS-CVRP/pull/20
- [x] better handling of duration constraints
- [ ] improve `CVRPLIB` to handle more general `.vrp` files, e.g. instances without coordinates 

### Testing
- [x] test for instances with duration constraints https://github.com/vidalt/HGS-CVRP/pull/22

**Comment by vidalt** [comment]
Amazing plan!

**Comment by chkwon** [comment]
With the release of v2.0.0, this is closed.
