### ISSUE TITLE
Cryptic error: `terminate called after throwing an instance of 'char const*'` when failing demand or distance checks

### ISSUE THREAD

**Issue by wouterkool** [vidalt/HGS-CVRP#2]
The code gives a very cryptic `terminate called after throwing an instance of 'char const*'` error when failing the distance or demand checks. This seems to be fixed by adding `std::string` after the throw keywords (as is done in other places in the code). See #1

**Comment by vidalt** [comment]
Thanks for noticing this, closed by pull request #1
