### ISSUE TITLE
great job

### ISSUE THREAD

**Issue by qtbgo** [vidalt/HGS-CVRP#3]
great job.
could it solve Leuven2 instance, which have 4000 customers.
see http://vrp.atd-lab.inf.puc-rio.br/index.php/en/
under Arnold, Gendreau and Sörensen (2017)

**Comment by vidalt** [comment]
Hello,
Thanks for your interest in this project,
The code should run but it would be very slow on very large instances, as the version of this repository calibrated for such cases.
If you wish to efficiently tackle such cases, I recommend that you include additional decomposition steps in the code (as described in the UHGS paper from 2014), reduce the termination criterion to 1000it without improvement (by using -it 1000 in the line of command), and rely on a reduced population size with mu=12, lambda=25, nbElite=3 and nbclose=2 at https://github.com/vidalt/HGS-CVRP/blob/b5263bbc9f0e85a14be85b412e1f1bf06781430b/Program/Params.h#L58-L61.
At least with those parameter adjustments, it will already be much faster. 
For safety, you can also include a hard time limit (for example 2h).
Kind Regards,
--Thibaut
