### ISSUE TITLE
Is there any way to feed an initial solution to the algorithm?

### ISSUE THREAD

**Issue by Regista6** [vidalt/HGS-CVRP#30]

**Comment by vidalt** [comment]
Dear @Regista6, 
My apologies for the delayed answer, this is a very easy functionality to add to the algorithm, at least through its C++ API. We will add this possibility ASAP. Would you be interested in feeding the solution as one of the starting individuals in the population, or as a starting point to apply a single local-search run for example?

**Comment by Regista6** [comment]
Hi,

Thanks for the reply. I think I am interested in the latter functionality but if you can add both those features, that would be great too. 

By the way, it is completely fine with me if you take your time with this. I don't have any urgent requirements!.

**Comment by vidalt** [comment]
Commit https://github.com/vidalt/HGS-CVRP/commit/82644d647b0b62a5df84ab529164aa4a1c5cd6c3 permits to construct an Individual from a solution file in CVRPLib format.

This permits, for example, to add an input solution in the initial population by adding the following two lines of code before the end of the generatePopulation() function:

`Individual randomIndiv(params,"<PATH_TO_INPUT_SOLUTION>");`
`addIndividual(randomIndiv, false);`

With this additional functionality the issue should be solved now
