### ISSUE TITLE
[bug] segfault if number of vehicles is too low

### ISSUE THREAD

**Issue by tdeenes** [vidalt/HGS-CVRP#4]
Thank you for the implementation, it gives very promising results in our use case. However, it seems the program segfaults if the number of vehicles is too low for the particular problem:
```
Program$ ./genvrp ../Instances/CVRP/CMT1.vrp  ../test.sol -seed 1 -veh 2
----- READING DATA SET: ../Instances/CVRP/CMT1.vrp
----- INSTANCE LOADED WITH 50 CLIENTS AND 2 VEHICLES
----- BUILDING INITIAL POPULATION
Segmentation fault (core dumped)
```
The code above runs the algorithm and returns the solution if `-veh` is increased to 5.

**Comment by vidalt** [comment]
Thank you for your interest in this project.
I have just modified the code (see commit cc12dcea339180f31c991de599b2e0521196aa95) to return an error message whenever the fleet size is not sufficient to serve the considered set of customers.
