### ISSUE TITLE
Unexpected Calculation of BiasedFitnesses

### ISSUE THREAD

**Issue by FeiLiu36** [vidalt/HGS-CVRP#41]
I am confused about the calculation of BiasedFitnesses.

The calculation of BiasedFitnesses seems not consistent with that given in the paper (Hybrid genetic search for the CVRP: Open-source implementation and SWAP* neighborhood)

In this HGS-CVRP code it looks like this:
https://github.com/vidalt/HGS-CVRP/blob/2d4d6731073c6d5b765529cec868dbfb7d0c049f/Program/Population.cpp#L82-L87

In the paper it is formulated as:
<img src="https://user-images.githubusercontent.com/40708416/211450752-b6b9d3a0-a6ab-4e04-8ff3-11186bd3e0f2.png" alt="drawing" width="300"/>

I suppose the difference is that the **divRank** in the source code is actually the ranking of fitness while **fitRank** is the ranking of diversity.

**Comment by vidalt** [comment]
I'm not sure to understand your issue completely. `divRank` and `fitRank` respectively evaluate the individual's rank (normalized in [0,1]) in terms of diversity contribution and cost. Then, `biasedFitness` calculates at line 87 exactly the announced formula...

**Comment by FeiLiu36** [comment]
> I'm not sure to understand your issue completely. `divRank` and `fitRank` respectively evaluate the individual's rank (normalized in [0,1]) in terms of diversity contribution and cost. Then, `biasedFitness` calculates at line 87 exactly the announced formula...

Thanks a lot for the quick reply! After reviewing the code, I am sorry to find out that it is actually a misunderstanding on my part. The vector 'ranking' stores both the distance and rank of fitness. The calculation of `divRank` and `fitRank` is exactly consistent with the formulation. I will close this issue.

**Comment by FeiLiu36** [comment]
I have just noticed a closed issue https://github.com/vidalt/HGS-CVRP/issues/21, which has already provided a detailed explanation of this one.
