### ISSUE TITLE
Temporal Distance or Spatial DIstance

### ISSUE THREAD

**Issue by MarcoMencucci** [vidalt/HGS-CVRP#46]
Is the distance matrix that we pass as input to the algorithm made of spatial or temporal distances? Because looking at the Individual.cpp section, it seems that the distances are indeed temporal! In case the distance are spatial, is it possible to use temporal distances?
Thank you in advance for your attention.

**Comment by vidalt** [comment]
It does not matter which unit of distance is used in a CVRP: cost, time, distance, or emissions, for example, as long as it's a fixed scalar for any (i,j) pair.
When duration constraints are activated (as in the case of the Golden instances), the constraint on duration (for each route) is applied to the sum of the distance and service time of the customers.
