### ISSUE TITLE
compiling a new shared library

### ISSUE THREAD

**Issue by MarcoMencucci** [vidalt/HGS-CVRP#48]
I apologize for all these issues, but these are doubts I need to clarify: I am using your algorithm along with a Python wrapper created by Changhyun Kwon. By installing the hygese library with pip, I am able to run the algorithm successfully in Python (except for the issue related to the previous duration_limit issue). I have modified the C code and compiled the shared library (following the instructions on your algorithm's GitHub page) to allow Changhyun Kwon's Python wrapper to use my modified version of C (the library in question is libhgscvrp.so). The tests conducted via the terminal are good and end with success. However, when I try to use the algorithm with the Python wrapper, I consistently get 0 iterations. Clearly, there is an issue! The folder where I copy libhgscvrp.so is the same folder where the "functional" library is installed using "pip install hygese". Additionally, there are differences in size between the library compiled following your instructions and the one downloaded via pip. Could you please provide some solutions to this problem?

I apologize for the inconvenience and thank you for your attention while awaiting your response.

**Comment by vidalt** [comment]
I apologize, but I can't investigate this issue; this repository is dedicated to maintaining the C/C++ code of HGS-CVRP. Any issue with the Python wrapper should be discussed in the Hygese projet.
