### ISSUE TITLE
Is it possible to let the vehicle return to the depot and start a new route?

### ISSUE THREAD

**Issue by tdeenes** [vidalt/HGS-CVRP#5]
It seems the current implementation enforces one route per vehicle. Assume we have one vehicle with CAPACITY 1 and two nodes each with DEMAND 1, and the DURATION is set to 5. Let the travel time between Depot -> 1 -> Depot equal 2 and Depot -> 2 -> Depot equal 2. I would like to extend the current implementation in such a way that it creates the following route: Route #1: 0 1 0 2 0. Can you maybe give me a hint how to start to implement this feature?

Of course in the actual use case we have multiple vehicles and many shops to serve.

**Comment by vidalt** [comment]
Thank you very much for your contribution.

The setting that you describe is typical of the "multi-trip" vehicle routing problem. See, for example, the following references for surveys on classic vehicle routing problem variants and a multi-trip algorithm:
https://www.sciencedirect.com/science/article/abs/pii/S0377221713002026
https://www.sciencedirect.com/science/article/abs/pii/S0377221719308422
https://www.sciencedirect.com/science/article/abs/pii/S0377221713005006

The HGS-CVRP code has been designed to be extremely compact, simple to read and use, and therefore it covers only the canonical variant of the vehicle routing problem (the capacitated vehicle routing problem) which does not allow multiple trips per vehicle. A quick question: do you have a total resource constraint on the trips assigned to a given vehicle (like a duration, or time constraint?). If this is not the case, you could simply generate more routes than there are vehicles (by setting a large enough number of vehicles in the code), and a-posteriori assign several routes to each vehicle.

**Comment by tdeenes** [comment]
Thanks for the references! Yes, the total duration of a route is fixed. You are right, otherwise I could just increase the nr of vehicles. Given the duration constraint, however, we could improve the solution even more (which is pretty astonishing either in its current form, by the way) by having multi-trip routes. I could see you implemented the "A Memetic Algorithm for the Multi Trip Vehicle Routing Problem" in c++. Can you maybe make it public or share it with me? Of course I know it will not be pluggable to this repository out-of-the-box, but it could probably help us with the implementation. (I already extended the current implementation with a second demand/capacity dimension.)

**Comment by vidalt** [comment]
You are right, depending on the number of routes, a specific approach designed for the "multi-trip" VRP could perform better. The code of "A Memetic Algorithm for the Multi-Trip Vehicle Routing Problem" was actually implemented by Diego Cattaruzza, I would suggest contacting him directly regarding this code (his contact information seems to be available on his website: https://sites.google.com/site/cattaruzzaxdiego/). Regarding this specific issue, I will now mark it as closed. Thank you very much for your feedback!
