### ISSUE TITLE
Could you provide a more detailed description of the dataset?

### ISSUE THREAD

**Issue by StevRamos** [vidalt/HGS-CVRP#6]
Hi, I'd like to use your code in java. It looks pretty good but I don't understand the structure of the datasets.  I was wondering if you have a more detailed description of it. Thanks in advance!

**Comment by vidalt** [comment]
Thank you for your interest in this project.
All instances are provided in TSPLib format, documented here:
http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp95.pdf
